definitions:
  Drink:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  Order:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      drink_id:
        description: foreign key
        type: integer
    type: object
info:
  contact:
    name: Your Name
  description: This system enables drink orders and should not be used for the forbidden
    Hungover Games.
  title: Order System
paths:
  /api/menu:
    get:
      description: Returns the menu of all drinks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Drink'
            type: array
      tags:
      - Menu
  /api/order:
    post:
      consumes:
      - application/json
      description: Adds an order to the db
      parameters:
      - description: Order
        in: body
        name: b
        required: true
        schema:
          $ref: '#/definitions/Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Order
  /api/order/all:
    get:
      description: Returns all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Order'
            type: array
      tags:
      - Order
  /api/order/total:
    get:
      description: Returns totalled orders (DrinkID → Amount)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              format: int64
              type: integer
            type: object
      tags:
      - Order
swagger: "2.0"
